# -*- coding: utf-8 -*-
"""22301242_Md. Sabbir Akon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQohd3MxE3K2fVAtqkItMagIF-4EGoLi
"""

from queue import PriorityQueue

h={}
g={}
ifile=open("/content/drive/MyDrive/CSE422/LAB_1/Input file.txt","r")
r=ifile.readlines()
for l in r:
    d=l.strip().split()
    h[d[0]]=int(d[1])
    g[d[0]]={}
    i=2
    while i<len(d):
        g[d[0]][d[i]]=int(d[i+1])
        i+=2

def astar(s,t):
    q=PriorityQueue()
    q.put((h[s],0,s,None))
    p={}
    c={}
    c[s]=0
    while not q.empty():
        f,gx,n,par=q.get()
        if n in p:
            continue
        p[n]=par
        if n==t:
            r=[]
            while n!=None:
                r.insert(0,n)
                n=p[n]
            path= "Path: "
            for i in range(len(r)):
                path+= str(r[i])
                if i<len(r)-1:
                    path+= "->"
            return path+ "\nTotal distance: " + str(gx) + "km"

        for k in g[n]:
            new_gx=gx+g[n][k]
            f=new_gx+h[k]
            if k not in c or new_gx<c[k]:
                c[k]=new_gx
                q.put((f,new_gx,k,n))
    return "No path found"

s="Arad"
d="Bucharest"
print(h)
print(g)
print(astar(s,d))