# -*- coding: utf-8 -*-
"""Md. Sabbir Akon_22301242_LAB04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upW9BQYW6RElDGrpvgb38jbluFaDvof2
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

f= "/content/drive/MyDrive/CSE422/Heart Disease.csv"
df= pd.read_csv(f)
print("file read")

print(df.head(2))
print("null check")
nul= df.isnull().sum()
print(nul)
simp= SimpleImputer()
df[['education','cigsPerDay','BPMeds','totChol','BMI','heartRate','glucose']]= simp.fit_transform(df[['education','cigsPerDay','BPMeds','totChol','BMI','heartRate','glucose']])
lb= LabelEncoder()
df['gender']= lb.fit_transform(df['gender'])

print("check after clean")
print(df.head(1))
out= df['Heart Disease (in next 10 years)']
df=df.drop('Heart Disease (in next 10 years)', axis=1)

xtrain, xtest, ytrain, ytest = train_test_split(df, out, test_size=0.2, random_state=2)
print("train shape:", xtrain.shape)

mod = RandomForestClassifier()
mod.fit(xtrain, ytrain)

print("model trained")
pre= mod.predict(xtest)
prob= mod.predict_proba(xtest)[:,1]

print("first few preds")
print(pre[:7])

ac= accuracy_score(ytest,pre)
print("acc is", acc)
conf= confusion_matrix(ytest,pre)
print("conf mat:")
print(conf)
rep= classification_report(ytest,pre)
print("report:")
print(rep)

auc= roc_auc_score(ytest,prob)
print("auc is",auc)

fprr,tprr,thr= roc_curve(ytest, prob)

plt.plot(fprr, tprr)
plt.plot([0,1],[0,1],'--')
plt.xlabel('fpr')
plt.ylabel('tpr')
plt.title('roc')
plt.show()